name: microsoft_clarity_plugin_example
description: "Demonstrates how to use the microsoft_clarity_plugin plugin."

environment:
  sdk: '>=3.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  microsoft_clarity_plugin:
    path: ../

  cupertino_icons: 1.0.8
  material_design_icons_flutter: 7.0.7296

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true